package com.example.eduaiplatform.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    AUTHENTICATION_FAILED,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    CONFLICT,
    UNSAFE_FILE_UPLOAD,
    EXTERNAL_SERVICE_ERROR,
    AI_PROVIDER_ERROR,
    AI_INVALID_API_KEY,
    AI_QUOTA_EXCEEDED,
    AI_RATE_LIMITED,
    AI_TIMEOUT,
    AI_BAD_REQUEST,
    AI_UNSUPPORTED_IMAGE,
    AI_RESPONSE_PARSE_ERROR,
    AI_RESPONSE_TRUNCATED,
    AI_INPUT_CONFLICT,
    AI_PROVIDER_UNAVAILABLE,
    AI_USAGE_LIMIT_EXCEEDED,
    INTERNAL_ERROR
}
